# Generated by Django 5.0.1 on 2024-02-05 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=50)),
                (
                    "deposit",
                    models.IntegerField(
                        choices=[(5, "5"), (10, "10"), (20, "20"), (50, "50"), (100, "100")]
                    ),
                ),
                ("is_seller", models.BooleanField()),
                ("is_buyer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount_available", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("product_name", models.CharField(max_length=30)),
                (
                    "seller_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.user"),
                ),
            ],
        ),
    ]
