# Generated by Django 5.0.1 on 2024-02-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_buyer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_seller",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("BUYER", "Buyer"), ("SELLER", "Seller")], default="BUYER", max_length=20
            ),
        ),
    ]
