# Generated by Django 5.0.1 on 2024-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_user_is_buyer_remove_user_is_seller_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="deposit",
            field=models.IntegerField(
                choices=[(5, "5"), (10, "10"), (20, "20"), (50, "50"), (100, "100")], null=True
            ),
        ),
    ]
